### ISSUE TITLE
20200713

### ISSUE THREAD

**Issue by woonjangahn** [woowacourse-teams/2020-zeze#20]
### 프로젝트 구성

- Spring Boot (Spring 5)
  - Java 8
  - Gradle
- MySQL (H2)
- TypeScript React
  - Redux / Recoil

### 이슈 할당

- 마크다운 파서: @YerinCho 
- 커스텀 마크다운: @lalize 
- 유저 인증: @jjj0611 
- 목록보기 / 프리젠테이션 (전체화면) 모드: @woonjangahn 
- S3 / 프리젠테이션 스키마: @lowoon 

### 할 일

- 다음주까지 공부할 것
  - 향후 학습내용은 계속 GitHub Wiki에 공유
  - TypeScript
    - 커리큘럼 오늘 중으로 전달: @woonjangahn 
  - Recoil, Redux(+ Redux Thunk, Saga)
    - 리액트 교재나 블로그 보면서 각자 해보기
  - Spring Security 각자 해보기
- 할당된 이슈 마일스톤 설정하기 (화요일까지)
- 지난 주 각자 High Priority 구현한 것 정리하기
  > 쓰레드로 달아주세요. (느낀 점, 배운 점)

**Comment by lowoon** [comment]
- front
프레임 워크에서 제공하는 모듈보다 직접 css를 짜서 사용하는 것이 원하는 화면을 만들 때 훨씬 좋다는 것을 느낄 수 있었습니다.  
javascript뿐만이 아니라 React도 다시 한번 복습하며 심화된 내용을 공부해야 앞으로의 프로젝트 진행에 있어 도움이 될 것이라고 생각했습니다.

- back
이전에 했던 내용들을 복습하면서 이전에는 이해가 가지 않던 부분들을 좀 더 이해하게 되었고, 많이 쓰이는 소셜 로그인을 실제로 구현해보며 다음에도 활용할 수 있겠다는 생각을 했습니다. 그러면서 Spring Security와 JPA에 대한 공부가 더 필요하다고 느꼈습니다.

오랜만에 하는 front와 back이라 처음에는 어색한 느낌이 있었지만 전에 했던 내용을 복습하며 조금 더 이해할 수 있었던 시간이라 좋았습니다.

**Comment by woonjangahn** [comment]
### Client 

- [Full Screen API](https://developer.mozilla.org/ko/docs/Web/Guide/DOM/Using_full_screen_mode)를 사용하는데 있어 브라우저별로 지원하는 DOM API가 상이하며, [fscreen](https://github.com/rafgraph/fscreen)과 같은 호환성을 지원하는 라이브러리를 사용해야 함.
- TypeScript를 처음으로 도입해보았는데, 일반 JavaScript 기반 프로젝트에서와 다르게 Type 유추와 Auto-complete 기능이 굉장히 잘 지원됨. 향후 TypeScript를 도입하기를 희망한 이유 역시 여기에서 오는 생산성 때문이었음.
- 마크다운 파서의 경우 [marked.js](https://github.com/markedjs/marked)를 사용했는데, 메타정보 파싱 등의 경우에 어려움을 겪었음. [showdown.js](https://github.com/showdownjs/showdown)라는 라이브러리도 있다하여 다음에 유명한 파서들을 가지고 비교해보는 시간을 가질 수 있으면 좋겠음.

### Server

- Spring Data JPA의 경우 기존에 학습을 어느정도 했으며, 이번 프로젝트에 있어 많은 기능을 사용하지는 않아도 된다는 생각으로 이번에는 Spring Boot 기반 프로젝트에 대해 전반적인 복습을 한다는 생각으로 다른 것들을 많이 사용해 봄.
- Swagger라는 API 문서화 도구를 사용해 봄. 다음과 같이 작성하게 됨. `Api~`에 해당하는 어노테이션들이 Swagger 관련 문법인데, 기존에 우아한테크코스에서 사용하는 Spring REST Docs에 비교하면 테스트 코드에 의존하는 문서를 작성하지 않아도 된다는 것이 장점이었고, 실제 API 페이지에서 테스트가 가능하다는 것 역시 편리했음. 하지만 컨트롤러 코드의 양이 늘어나 한편으로는 가독성을 해칠 수 있다는 것이 단점으로 느껴짐. 그러나 충분히 도입을 검토해봐도 될 것 같음.

```java
@Api(tags = {"1. Sign"})
@RequiredArgsConstructor
@RestController
@RequestMapping("/v1")
public class SignController {
    private final UserRepository users;
    private final JwtTokenProvider jwtTokenProvider;
    private final ResponseService responseService;
    private final PasswordEncoder passwordEncoder;

    @ApiOperation(value = "로그인", notes = "이메일 로그인을 한다.")
    @PostMapping("/signin")
    public SingleResult<String> signIn(
            @ApiParam(value = "회원 이메일", required = true)
            @RequestParam String email,
            @ApiParam(value = "비밀번호", required = true)
            @RequestParam String password
    ) {
        User user = users.findByEmail(email).orElseThrow(EmailAuthorizationException::new);
        if (!passwordEncoder.matches(password, user.getPassword())) {
            throw new EmailAuthorizationException();
        }
        return responseService.getSingleResult(jwtTokenProvider.createToken(String.valueOf(user.getId()), user.getRoles()));
    }
}
```

- 여러 데이터를 내보낼 때 공통적인 포맷을 갖추는 DTO를 제네릭을 이용해 만들어 사용했는데, 응답에 일관성이 있어서 좋았음. 또한 반환할 객체가 없는 요청이나 Exception들에 대해서도 DTO를 만들어 사용했는데, 같은 장점을 취했음. 에러 코드와 메세지를 항상 받아 어떤 오류가 났는지 클라이언트 측에서 확인할 수 있어서 편리함.

```java
// MultipleResults.java
@Getter
@Setter
public class MultipleResults<T> extends CommonResult {
    private List<T> data;
}
```

```java
// SingleResult.java
@Getter
@Setter
public class SingleResult<T> extends CommonResult {
    private T data;
}
```

```java
// Service
public <T> SingleResult<T> getSingleResult(T data) {
    SingleResult<T> result = new SingleResult<>();
    result.setData(data);
    setSuccessResult(result);
    return result;
}
```

```java
// Controller
@PutMapping("/users")
public SingleResult<User> modify(
        @RequestParam Long id,
        @RequestParam String email,
        @RequestParam String name
) {
    User user = User.builder()
            .id(id)
            .email(email)
            .name(name)
            .build();
    return responseService.getSingleResult(users.save(user));
}
```

```java
// Result 관련 DTO
public class CommonResult {

    @ApiModelProperty(value = "응답 성공 여부: true / false")
    private boolean success;

    @ApiModelProperty(value = "응답 코드 번호: >= 0 정상 / < 0 비정상")
    private int code;

    @ApiModelProperty(value = "응답 메세지")
    private String message;
}
```

```java
// ControllerAdvice
@ExceptionHandler(Exception.class)
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
protected CommonResult defaultException(HttpServletRequest request, Exception exception) {
    System.out.println(exception.getMessage());
    return responseService.getFailResult(Integer.parseInt(getMessage("unknown.code")), getMessage("unknown.message"));
}

@ExceptionHandler(UserNotFoundException.class)
@ResponseStatus(HttpStatus.NOT_FOUND)
protected CommonResult userNotFoundException(HttpServletRequest request, UserNotFoundException exception) {
    return responseService.getFailResult(Integer.parseInt(getMessage("userNotFound.code")), getMessage("userNotFound.message"));
}
```

- MessageSource를 적극적으로 활용했는데, `yml` 형식의 데이터에서 값을 가져올 수 있어 특정 값들에 대해 은닉화 및 관리를 할 수 있다는 점이 매력적이었음. Configuration이 다소 필요했어서 이를 첨부함. `yml` 형식을 MessageSource로 사용하기 위해 `implementation 'net.rakugakibox.util:yaml-resource-bundle:1.1'` 라이브러리를 사용했음.

```java
// MessageConfiguration.java
@Configuration
public class MessageConfiguration implements WebMvcConfigurer {
    @Bean
    public LocaleResolver localeResolver() {
        SessionLocaleResolver resolver = new SessionLocaleResolver();
        resolver.setDefaultLocale(Locale.KOREAN);
        return resolver;
    }

    @Bean
    public LocaleChangeInterceptor localeChangeInterceptor() {
        LocaleChangeInterceptor interceptor = new LocaleChangeInterceptor();
        interceptor.setParamName("lang");
        return interceptor;
    }

    @Override
    public void addInterceptors(InterceptorRegistry registry) {
        registry.addInterceptor(localeChangeInterceptor());
    }

    @Bean
    public MessageSource messageSource(
            @Value("${spring.messages.basename}") String basename,
            @Value("${spring.messages.encoding}") String encoding
    ) {
        YamlMessageSource messageSource = new YamlMessageSource();
        messageSource.setBasename(basename);
        messageSource.setDefaultEncoding(encoding);
        messageSource.setAlwaysUseMessageFormat(true);
        messageSource.setUseCodeAsDefaultMessage(true);
        messageSource.setFallbackToSystemLocale(true);
        return messageSource;
    }

    private class YamlMessageSource extends ResourceBundleMessageSource {
        @Override
        protected ResourceBundle doGetBundle(String basename, Locale locale) throws MissingResourceException {
            return ResourceBundle.getBundle(basename, locale, YamlResourceBundle.Control.INSTANCE);
        }
    }

```

```yml
# application.yml
server:
  port: 8080
spring:
  jpa:
    show-sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: hodol123!@#
  url:
    base: http://localhost:8080
  social:
    github:
      client_id: 8340716e3b284c9cd9c0
      client_secret: 8da9800e103394bb64d24fda8817d2a163774a41
      redirect_uri: /oauth/github
      url:
        profile: https://api.github.com/user
        login: https://github.com/login/oauth/authorize
        token: https://github.com/login/oauth/access_token
```

```yml
# resources/i18n/exception_en.yml
unknown:
  code: "-9999"
  message: "Unknown error has occured."
userNotFound:
  code: "-1000"
  message: "Member does not exists."
emailAuthorizationFailed:
  code: "-1001"
  message: "Your account does not exist or your email or password is incorrect."
entryPointException:
  code: "-1002"
  message: "You do not have permission to access this resource."
accessDenied:
  code: "-1003"
  message: "A resource that can not be accessed with the privileges it has."
oauthException:
  code: "-1004"
  message: "An error occurred during oauth process."
```

- Spring Security를 사용해보았는데, 난이도가 있었으며 `oauth2-client`를 사용함에 있어서는 GitHub을 세션을 이용해 인증을 진행할 수는 있었으나 토큰을 받는 방법을 잘 모르겠어서 포기하고 `RestTemplate`를 사용해서 요청을 보냈었음. DispatcherServlet을 거치기 전 Filter에서 사용자 확인이 진행되기 때문에 이에 대한 Exception을 설정파일에서 `.exceptionHandling().accessDeniedHandler(new InvalidAccessDeniedHandler()).and().exceptionHandling().authenticationEntryPoint(new ForwardAuthenticationEntryPoint())` 등을 사용해 설정해주는 것이 흥미로웠음.
- Security의 경우 전반적으로 Adapter 구현체에서 설정을 진행해야하는데, 본인이 작성한 Adapter은 다음과 같음.

```java
@EnableGlobalMethodSecurity(securedEnabled = true, prePostEnabled = true) // 이것을 사용하면 모든 Controller가 기본적으로 열리며 이에 @Secured라는 어노테이션을 붙임을 통해 로그인된 유저만 받을 수 있음.
@RequiredArgsConstructor
@Configuration
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
    private final JwtTokenProvider jwtTokenProvider;

    @Bean
    public PasswordEncoder passwordEncoder() {
        return PasswordEncoderFactories.createDelegatingPasswordEncoder();
    }

    @Bean
    public RestTemplate restTemplate() {
        return new RestTemplate();
    }

    @Bean
    @Override
    public AuthenticationManager authenticationManagerBean() throws Exception {
        return super.authenticationManagerBean();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .httpBasic().disable()
                .csrf().disable()
                .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
//          .and()
//            .authorizeRequests()
//              .antMatchers("/*/signin", "/*/signup").permitAll()
//              .antMatchers(HttpMethod.GET, "/exception/**", "helloworld/**").permitAll()
//              .antMatchers("/*/users").hasRole("ADMIN")
//              .anyRequest().hasRole("USER")
                .and()
                .exceptionHandling().accessDeniedHandler(new InvalidAccessDeniedHandler())
                .and()
                .exceptionHandling().authenticationEntryPoint(new ForwardAuthenticationEntryPoint())
                .and()
                .addFilterBefore(new JwtAuthenticationFilter(jwtTokenProvider), UsernamePasswordAuthenticationFilter.class);
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring().antMatchers("/v2/api-docs", "/swagger-resources/**", "/swagger-ui.html", "/webjars/**", "/swagger/**");
    }
}
```

- JWT 만드는 것은 여전히 어려운 것 같음 ㅠㅠ
